### ISSUE TITLE
pass current_user to MyRoutes

### ISSUE THREAD

**Issue by tgoldenberg** [mariopeixoto/react-router-rails#9]
How would I pass in my current_user.to_json in my <%= react_router "MyRoutes" %>

I tried to pass it in as <%= react_router "MyRoutes", @data %>, but it wasn't showing up in my React components. 

Any thoughts?

**Comment by mariopeixoto** [comment]
The second argument of the react_router helper is the location strategy. You can use either HistoryLocation or HashLocation:

```
<%= react_router "MyRoutes", 'HistoryLocation', @data %>
```

or 

```
<%= react_router "MyRoutes", 'HashLocation', @data %>
```

Please check the react-router docs (https://github.com/rackt/react-router/tree/v0.13.3) for more information on the location strategy.

Be careful on what you expose in the @data variable , the value will be added into a html attribute and the JS will retrieve that data in order to render the page.

**Comment by tgoldenberg** [comment]
Awesome, thank you!

**Comment by joaovpmamede** [comment]
@mariopeixoto you say that:

```
the value will be added into a html attribute and the JS will retrieve that data in order to render the page.
```

Does that also happen with prerender_location set?

Right now I'm having this weird behaviour that, my components are indeed prerendered but it always try to run the same code again (components) but without props.

**Comment by mariopeixoto** [comment]
@joaovpmamede It doesn't. In theory you would not need the prerender_location on the client side because the prerender_location represents the current url. Could you create an issue and provide an example or specific information on how to reproduce?

**Comment by joaovpmamede** [comment]
Well maybe I'm doing some wrong or not understanding prerender at all but with react rails gem, the server rendering puts on the html element the data-react-props attribute.

[server-rendering](https://github.com/reactjs/react-rails#server-rendering)

Anyway even with react rails my components render twice, first on the server and second on the client.

**Comment by mariopeixoto** [comment]
@joaovpmamede After receiving the pre-rendered html on the client, React has to plug itself. It checks whether the html is correct or not by using some checksums and when it's wrong it renders everything again. That is the correct behaviour.

That's why we set the props (@data) into a html attribute, in order to reuse on the client side.

The wrong thing here is to re-render without the props. What version of the gem are you using?

**Comment by joaovpmamede** [comment]
Thanks for explaining.

Last one: 0.13.3

This is what I get on devtools
![screenshot 2015-07-23 20 21 37](https://cloud.githubusercontent.com/assets/1040722/8858579/8162345c-3178-11e5-9daf-2bd0dfcf03be.jpg)

``` ruby
<%= react_router 'JournalRoutes', 'HistoryLocation', @data, { prerender_location: root_path } %>
```

``` javascript
const Route = ReactRouter.Route;

this.JournalRoutes = (
  <Route handler={App}>
    <Route name='home' handler={Journal} path='/' />
  </Route>
);
```

```
 It checks whether the html is correct or not by using some checksums and when it's wrong it renders everything again.
```

That's weird because I don't get any warnings, my html/components seem ok, but with react rails I get all of my components rerendered no matter what (I've put a console.log on render method and it fires twice everytime I refresh).

**Comment by mariopeixoto** [comment]
@joaovpmamede Can you try use the version below:

```
gem 'react-router-rails', :git => 'git@github.com:mariopeixoto/react-router-rails.git', :branch => 'v0.13.3p1'
```

Let me know if it solves your problem.

**Comment by joaovpmamede** [comment]
Yup, it renders the data-react-router-data just fine :+1: 
Thanks!

**Comment by mariopeixoto** [comment]
I'll publish a new version shortly.
